2020-07-07 12:33:58.7235|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-07-07 12:34:00.9299|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-07-07 12:34:01.0619|ERROR|WedigITCRM.Startup|start of Configure method
2020-07-07 12:34:02.9972|ERROR|WedigITCRM.Startup|end of Configure method
2020-07-07 12:34:10.7302|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-07-07 12:34:10.8692|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to frontpage controller index action
2020-07-07 12:34:30.2975|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-07-07 12:34:30.3166|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-07-07 18:19:24.1584|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-07-07 18:19:25.7156|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-07-07 18:19:25.8523|ERROR|WedigITCRM.Startup|start of Configure method
2020-07-07 18:19:26.8487|ERROR|WedigITCRM.Startup|end of Configure method
2020-07-07 18:19:30.6210|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-07-07 18:19:30.7331|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to frontpage controller index action
2020-07-07 18:19:48.6729|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-07-07 18:19:48.6926|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-07-07 18:22:44.5970|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2020-07-07 18:22:44.7299|ERROR|WedigITCRM.Startup|{"UserId":"6c1e27cf-820e-4335-b9a5-7ed1142c531c","UserName":"johnpetersen1959@gmail.com","CompanyId":"13024","CompanyName":"wedigIT ApS","Type":null,"Title":"Unexpected Error","Status":500,"Detail":"The remote server returned an error: (404) Not Found.\r\n                                         \r\n\r\n                                            at System.Net.HttpWebRequest.GetResponse()\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request)\r\n   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)\r\n   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)\r\n   at System.Net.WebClient.DownloadString(Uri address)\r\n   at System.Net.WebClient.DownloadString(String address)\r\n   at WedigITCRM.DineroAPI.DineroInvoice.getInvoicesByIntervalFromDinero(DateTime fromDate, DateTime toDate) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\DineroAPI\\DineroInvoice.cs:line 37\r\n   at WedigITCRM.Controllers.PurchaseOrderController.getTotalSoldAmountForStockItem(DateTime fromDate, DateTime toDate, Guid DineroStockitemId, CompanyAccount companyAccount) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\Controllers\\PurchaseOrderController.cs:line 891\r\n   at WedigITCRM.Controllers.PurchaseOrderController.createBudgetLineFromItemLine(PurchaseBudgetLineModel model, CompanyAccount companyAccount) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\Controllers\\PurchaseOrderController.cs:line 875\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","Instance":"fea698e8-7d36-4d79-83e5-b7c8945c25d8","Extensions":{}}
2020-07-07 18:29:32.4508|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2020-07-07 18:29:32.4987|ERROR|WedigITCRM.Startup|{"UserId":"6c1e27cf-820e-4335-b9a5-7ed1142c531c","UserName":"johnpetersen1959@gmail.com","CompanyId":"13024","CompanyName":"wedigIT ApS","Type":null,"Title":"Unexpected Error","Status":500,"Detail":"The remote server returned an error: (404) Not Found.\r\n                                         \r\n\r\n                                            at System.Net.HttpWebRequest.GetResponse()\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request)\r\n   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)\r\n   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)\r\n   at System.Net.WebClient.DownloadString(Uri address)\r\n   at System.Net.WebClient.DownloadString(String address)\r\n   at WedigITCRM.DineroAPI.DineroInvoice.getInvoicesByIntervalFromDinero(DateTime fromDate, DateTime toDate) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\DineroAPI\\DineroInvoice.cs:line 37\r\n   at WedigITCRM.Controllers.PurchaseOrderController.getTotalSoldAmountForStockItem(DateTime fromDate, DateTime toDate, Guid DineroStockitemId, CompanyAccount companyAccount) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\Controllers\\PurchaseOrderController.cs:line 891\r\n   at WedigITCRM.Controllers.PurchaseOrderController.createBudgetLineFromItemLine(PurchaseBudgetLineModel model, CompanyAccount companyAccount) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\Controllers\\PurchaseOrderController.cs:line 875\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","Instance":"1771676f-222a-4991-babd-87f21952a71b","Extensions":{}}
2020-07-07 18:33:20.9639|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-07-07 18:33:22.8583|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-07-07 18:33:22.9985|ERROR|WedigITCRM.Startup|start of Configure method
2020-07-07 18:33:24.0158|ERROR|WedigITCRM.Startup|end of Configure method
2020-07-07 18:33:30.6503|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-07-07 18:33:30.7280|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-07-07 18:38:51.7013|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2020-07-07 18:38:52.0750|ERROR|WedigITCRM.Startup|{"UserId":"6c1e27cf-820e-4335-b9a5-7ed1142c531c","UserName":"johnpetersen1959@gmail.com","CompanyId":"13024","CompanyName":"wedigIT ApS","Type":null,"Title":"Unexpected Error","Status":500,"Detail":"The remote server returned an error: (404) Not Found.\r\n                                         \r\n\r\n                                            at System.Net.HttpWebRequest.GetResponse()\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request)\r\n   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)\r\n   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)\r\n   at System.Net.WebClient.DownloadString(Uri address)\r\n   at System.Net.WebClient.DownloadString(String address)\r\n   at WedigITCRM.DineroAPI.DineroInvoice.getInvoicesByIntervalFromDinero(DateTime fromDate, DateTime toDate) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\DineroAPI\\DineroInvoice.cs:line 37\r\n   at WedigITCRM.Controllers.PurchaseOrderController.getTotalSoldAmountForStockItem(DateTime fromDate, DateTime toDate, Guid DineroStockitemId, CompanyAccount companyAccount) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\Controllers\\PurchaseOrderController.cs:line 891\r\n   at WedigITCRM.Controllers.PurchaseOrderController.createBudgetLineFromItemLine(PurchaseBudgetLineModel model, CompanyAccount companyAccount) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\Controllers\\PurchaseOrderController.cs:line 875\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","Instance":"f14c2e33-fd42-4721-b3d0-0193d434b9ef","Extensions":{}}
2020-07-07 18:42:03.0934|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-07-07 18:42:04.9884|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-07-07 18:42:05.2631|ERROR|WedigITCRM.Startup|start of Configure method
2020-07-07 18:42:06.1162|ERROR|WedigITCRM.Startup|end of Configure method
2020-07-07 18:42:14.4716|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-07-07 18:42:16.3321|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-07-07 18:43:45.4269|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2020-07-07 18:43:45.9081|ERROR|WedigITCRM.Startup|{"UserId":"6c1e27cf-820e-4335-b9a5-7ed1142c531c","UserName":"johnpetersen1959@gmail.com","CompanyId":"13024","CompanyName":"wedigIT ApS","Type":null,"Title":"Unexpected Error","Status":500,"Detail":"The remote server returned an error: (404) Not Found.\r\n                                         \r\n\r\n                                            at System.Net.HttpWebRequest.GetResponse()\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request)\r\n   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)\r\n   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)\r\n   at System.Net.WebClient.DownloadString(Uri address)\r\n   at System.Net.WebClient.DownloadString(String address)\r\n   at WedigITCRM.DineroAPI.DineroInvoice.getInvoicesByIntervalFromDinero(DateTime fromDate, DateTime toDate) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\DineroAPI\\DineroInvoice.cs:line 37\r\n   at WedigITCRM.Controllers.PurchaseOrderController.getTotalSoldAmountForStockItem(DateTime fromDate, DateTime toDate, Guid DineroStockitemId, CompanyAccount companyAccount) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\Controllers\\PurchaseOrderController.cs:line 891\r\n   at WedigITCRM.Controllers.PurchaseOrderController.createBudgetLineFromItemLine(PurchaseBudgetLineModel model, CompanyAccount companyAccount) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\Controllers\\PurchaseOrderController.cs:line 875\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","Instance":"ef628401-0ae4-4537-8e62-8793ade85ef7","Extensions":{}}
2020-07-07 18:54:42.5120|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-07-07 18:54:44.2586|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-07-07 18:54:44.4093|ERROR|WedigITCRM.Startup|start of Configure method
2020-07-07 18:54:45.3462|ERROR|WedigITCRM.Startup|end of Configure method
2020-07-07 18:54:54.7277|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-07-07 18:54:54.8953|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-07-07 19:02:27.2788|ERROR|WedigITCRM.Maintenance.SynchronizeDineroContactsService|The SSL connection could not be established, see inner exception. Authentication failed because the remote party has closed the transport stream.nyxium stack trace:    at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at WedigITCRM.DineroAPI.DineroContacts.getContactsFromDinero(String LastupdatedDateTime, Int32 page, Int32 pageSize) in C:\Users\John\source\repos\WedigITCRM\WedigITCRM\DineroAPI\DineroContacts.cs:line 42
   at WedigITCRM.Maintenance.SynchronizeDineroContactsService.SynchronizeDineroContacts(Object state) in C:\Users\John\source\repos\WedigITCRM\WedigITCRM\Maintenance\SynchronizeDineroService.cs:line 102
2020-07-07 19:08:44.7119|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-07-07 19:08:47.6638|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-07-07 19:08:47.9395|ERROR|WedigITCRM.Startup|start of Configure method
2020-07-07 19:08:54.1270|ERROR|WedigITCRM.Startup|end of Configure method
2020-07-07 19:09:05.1584|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-07-07 19:09:05.3991|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-07-07 21:54:27.5278|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-07-07 21:54:29.3563|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-07-07 21:54:29.7472|ERROR|WedigITCRM.Startup|start of Configure method
2020-07-07 21:54:30.5768|ERROR|WedigITCRM.Startup|end of Configure method
2020-07-07 21:54:34.6810|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-07-07 21:54:34.9906|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to frontpage controller index action
2020-07-07 21:54:46.1649|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-07-07 21:54:46.5217|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-07-07 22:07:10.4154|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-07-07 22:07:11.7476|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-07-07 22:07:11.8771|ERROR|WedigITCRM.Startup|start of Configure method
2020-07-07 22:07:12.4210|ERROR|WedigITCRM.Startup|end of Configure method
2020-07-07 22:07:15.7287|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-07-07 22:07:15.7809|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-07-07 22:21:19.9118|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-07-07 22:21:21.5169|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-07-07 22:21:21.6192|ERROR|WedigITCRM.Startup|start of Configure method
2020-07-07 22:21:22.5055|ERROR|WedigITCRM.Startup|end of Configure method
2020-07-07 22:21:26.3237|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-07-07 22:21:26.4163|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-07-07 23:02:49.1270|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-07-07 23:02:51.0024|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-07-07 23:02:51.1855|ERROR|WedigITCRM.Startup|start of Configure method
2020-07-07 23:02:52.0989|ERROR|WedigITCRM.Startup|end of Configure method
2020-07-07 23:02:57.6771|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-07-07 23:02:57.7782|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
