2020-06-21 00:11:02.8096|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 00:11:03.9262|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 00:11:04.0241|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 00:11:04.6470|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 00:11:16.5501|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 00:11:16.6733|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 00:12:54.8854|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2020-06-21 00:12:55.4002|ERROR|WedigITCRM.Startup|{"UserId":"6c1e27cf-820e-4335-b9a5-7ed1142c531c","UserName":"johnpetersen1959@gmail.com","CompanyId":"13024","CompanyName":"wedigIT ApS","Type":null,"Title":"Unexpected Error","Status":500,"Detail":"Value cannot be null. (Parameter 's')\r\n                                         \r\n\r\n                                            at System.Int32.Parse(String s)\r\n   at WedigITCRM.Controllers.PurchaseOrderController.saveOrderLine(PurchaseOrderLineModel model, CompanyAccount companyAccount) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\Controllers\\PurchaseOrderController.cs:line 397\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","Instance":"224bcfa4-8d4b-4de4-9f29-ffb32b8296fd","Extensions":{}}
2020-06-21 00:22:50.5207|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 00:22:51.8009|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 00:22:51.9473|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 00:22:53.8830|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 00:23:00.3666|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 00:23:00.4122|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 00:26:45.0783|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 00:26:46.2031|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 00:26:46.3132|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 00:26:46.8872|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 00:26:50.8901|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 00:26:51.1849|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 00:37:47.5521|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 00:37:48.6509|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 00:37:48.8163|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 00:37:49.4056|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 00:37:55.8101|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 00:37:55.8967|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 00:41:27.0653|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2020-06-21 00:41:27.2969|ERROR|WedigITCRM.Startup|{"UserId":"6c1e27cf-820e-4335-b9a5-7ed1142c531c","UserName":"johnpetersen1959@gmail.com","CompanyId":"13024","CompanyName":"wedigIT ApS","Type":null,"Title":"Unexpected Error","Status":500,"Detail":"Could not find file 'C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\wwwroot\\CustomerAttachments\\514ccc67-e9c1-44e4-b835-83e967753696_purchaseOrder.pdf'.\r\n                                         \r\n\r\n                                            at System.IO.FileInfo.get_Length()\r\n   at WedigITCRM.Controllers.PurchaseOrderController.sendPurchaseOrder(Int32 purchaseOrderId, CompanyAccount companyAccount) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\Controllers\\PurchaseOrderController.cs:line 633\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","Instance":"944fa928-e92a-4431-9699-f1eee7582df9","Extensions":{}}
2020-06-21 00:43:50.3971|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 00:43:51.4138|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 00:43:51.4940|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 00:43:52.0791|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 00:43:56.6122|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 00:43:56.6606|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 09:23:51.7990|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 09:23:53.1194|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 09:23:53.2226|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 09:23:53.7252|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 09:23:55.7834|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 09:23:55.8202|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to frontpage controller index action
2020-06-21 09:24:39.7383|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 09:24:39.7637|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 10:16:57.4537|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 10:16:58.5721|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 10:16:58.6888|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 10:16:59.3241|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 10:17:00.7490|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 10:17:00.8129|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to frontpage controller index action
2020-06-21 10:17:10.6732|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 10:17:10.6936|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 10:17:18.2569|ERROR|Microsoft.EntityFrameworkCore.Query|An exception occurred while iterating over the results of a query for context type 'WedigITCRM.AppDbContext'.
System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
2020-06-21 10:22:08.0518|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2020-06-21 10:22:08.2140|ERROR|WedigITCRM.Startup|{"UserId":"6c1e27cf-820e-4335-b9a5-7ed1142c531c","UserName":"johnpetersen1959@gmail.com","CompanyId":"13024","CompanyName":"wedigIT ApS","Type":null,"Title":"Unexpected Error","Status":500,"Detail":"Unable to cast object of type 'System.Int32' to type 'System.String'.\r\n                                         \r\n\r\n                                            at Microsoft.Data.SqlClient.SqlBuffer.get_String()\r\n   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)\r\n   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at WedigITCRM.Controllers.PurchaseOrderController.Index(Nullable`1 page, String receivedStatus, String vendorId, String purchaseDocumentNumber, String searchFromDate, String searchToDate, CompanyAccount companyAccount) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\Controllers\\PurchaseOrderController.cs:line 63\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","Instance":"ee5b8e00-d523-4002-b452-3631bf36556c","Extensions":{}}
2020-06-21 10:26:43.7929|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 10:26:43.9666|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 10:27:17.5743|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 10:27:17.6986|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 10:27:38.9719|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 10:27:40.3064|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 10:27:40.4161|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 10:27:41.0622|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 10:27:42.3308|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 10:27:42.4066|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to frontpage controller index action
2020-06-21 10:27:50.3942|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 10:27:50.4223|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 10:35:50.2502|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 10:35:51.3949|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 10:35:51.4905|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 10:35:52.0155|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 10:35:52.9062|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 10:35:53.6337|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to frontpage controller index action
2020-06-21 10:36:01.6925|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 10:36:01.7154|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 10:40:21.7727|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 10:40:22.7803|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 10:40:22.9037|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 10:40:23.5120|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 10:40:24.3083|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 10:40:24.3517|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to frontpage controller index action
2020-06-21 10:40:40.3148|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 10:40:40.3562|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 10:58:03.9076|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 10:58:04.8557|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 10:58:04.9311|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 10:58:05.6044|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 10:58:06.6887|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 10:58:07.2300|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to frontpage controller index action
2020-06-21 10:58:14.4755|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 10:58:14.4957|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 11:04:14.8440|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 11:04:15.6764|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 11:04:15.7582|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 11:04:16.7099|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 11:04:20.1838|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 11:04:20.2457|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 11:12:52.3028|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 11:12:54.1495|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 11:12:54.2400|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 11:12:54.8778|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 11:12:59.7077|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 11:13:00.3562|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 11:21:44.7196|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 11:21:45.6561|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 11:21:45.7785|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 11:21:46.3596|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 11:21:50.7962|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 11:21:50.8760|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 11:33:48.7330|ERROR|WedigITCRM.Maintenance.SynchronizeDineroContactsService|The remote server returned an error: (502) Bad Gateway.nyxium stack trace:    at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at WedigITCRM.DineroAPI.DineroContacts.getContactsFromDinero(String LastupdatedDateTime, Int32 page, Int32 pageSize) in C:\Users\John\source\repos\WedigITCRM\WedigITCRM\DineroAPI\DineroContacts.cs:line 42
   at WedigITCRM.Maintenance.SynchronizeDineroContactsService.SynchronizeDineroContacts(Object state) in C:\Users\John\source\repos\WedigITCRM\WedigITCRM\Maintenance\SynchronizeDineroService.cs:line 102
2020-06-21 11:44:26.1766|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 11:44:27.1329|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 11:44:27.2012|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 11:44:27.8380|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 11:44:32.1331|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 11:44:32.1886|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 12:08:08.3915|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 12:08:09.3282|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 12:08:09.4107|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 12:08:10.0389|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 12:08:15.4661|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 12:08:15.5390|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 12:16:58.7547|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 12:16:59.7178|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 12:16:59.7958|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 12:17:00.3688|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 12:17:04.0972|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 12:17:04.2367|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 23:10:39.8635|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 23:10:41.8647|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 23:10:42.0080|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 23:10:43.9330|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 23:10:53.1843|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 23:10:53.3009|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to frontpage controller index action
2020-06-21 23:13:54.0978|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 23:13:54.1320|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 23:45:51.1207|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 23:45:52.8745|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 23:45:53.1120|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 23:45:54.1585|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 23:45:57.4242|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 23:45:57.4749|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to frontpage controller index action
2020-06-21 23:46:07.7227|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 23:46:07.7517|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 23:48:00.9705|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2020-06-21 23:48:01.0755|ERROR|WedigITCRM.Startup|{"UserId":"6c1e27cf-820e-4335-b9a5-7ed1142c531c","UserName":"johnpetersen1959@gmail.com","CompanyId":"13024","CompanyName":"wedigIT ApS","Type":null,"Title":"Unexpected Error","Status":500,"Detail":"The model item passed into the ViewDataDictionary is of type 'WedigITCRM.ViewModels.PurchaseOrderReceiveViewModel', but this ViewDataDictionary instance requires a model item of type 'WedigITCRM.ViewModels.PurchaseOrderViewModel'.\r\n                                         \r\n\r\n                                            at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(Object value)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(ViewDataDictionary source, Object model, Type declaredModelType)\r\n   at lambda_method(Closure , ViewDataDictionary )\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorPagePropertyActivator.CreateViewDataDictionary(ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorPagePropertyActivator.Activate(Object page, ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.Activate(IRazorPage page, ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)\r\n   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","Instance":"2939e5ab-f095-48fe-a366-cee8630b31f4","Extensions":{}}
2020-06-21 23:48:45.3797|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2020-06-21 23:48:45.4320|ERROR|WedigITCRM.Startup|{"UserId":"6c1e27cf-820e-4335-b9a5-7ed1142c531c","UserName":"johnpetersen1959@gmail.com","CompanyId":"13024","CompanyName":"wedigIT ApS","Type":null,"Title":"Unexpected Error","Status":500,"Detail":"The model item passed into the ViewDataDictionary is of type 'WedigITCRM.ViewModels.PurchaseOrderReceiveViewModel', but this ViewDataDictionary instance requires a model item of type 'WedigITCRM.ViewModels.PurchaseOrderViewModel'.\r\n                                         \r\n\r\n                                            at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(Object value)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(ViewDataDictionary source, Object model, Type declaredModelType)\r\n   at lambda_method(Closure , ViewDataDictionary )\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorPagePropertyActivator.CreateViewDataDictionary(ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorPagePropertyActivator.Activate(Object page, ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.Activate(IRazorPage page, ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)\r\n   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","Instance":"dd34a653-e150-476f-89e7-694a9e294abc","Extensions":{}}
